### ISSUE TITLE
Understanding iterations vs runs

### ISSUE THREAD

**Issue by yngtodd** [zygmuntz/hyperband#8]
Looking over the results from one of my runs, I am seeing both a number of `iterations` and a number of `runs`? Can you explain the difference between these two?

How would I go about setting up an experiment where there would be 50 pulls of the bandits? I assume that is setting the `run` parameter?

**Comment by zygmuntz** [comment]
A "run" refers to trying a configuration, running the model for a number of iterations. It's what you call a pull.

The total number of runs is controlled by hyperband's  internal hyperparams, s and eta if memory serves.

See http://fastml.com/tuning-hyperparams-fast-with-hyperband/ for explanation of matters such as those two.
